export const SUCCESS = "SUCCESS"
export const FAILURE = "FAILURE"
export const USER_INPUT = "USER_INPUT"
export const INCREMENT ="INCREMENT"
export const DECREMENT ="DECREMENT"
export const REQUESTED_DATA = "REQUESTED_DATA"
export const REQUESTED_DATA_SUCCEEDED ="REQUESTED_DATA_SUCCEEDED"
export const REQUESTED_DATA_FAILED ="REQUESTED_DATA_FAILED"
export const FETCHED_DATA = "FETCHED_DATA"

export const CREATE_EVENT = "CREATE_EVENT"
export const UPDATE_EVENT = "UPDATE_EVENT"
export const DELETE_EVENT = "DELETE_EVENT"

